# Generated by Django 3.2 on 2021-04-20 03:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 20, 3, 27, 10, 799006, tzinfo=utc)),
        ),
    ]
